languages: [ 'telugu', 'hindi' ]
telugu:
  ga: 
    name: 'Great Andhra'
    url: "http://www.greatandhra.com/reviews.php"
    css_path:  "div.movies_page_news a"
    base_url: ""
    rating_css_path:  "html body div.content p strong span"     
  ib: 
    name: 'Idle Brain'
    url: "http://idlebrain.com/movie/archive/index.html"
    css_path:  "html body table tr td table tr td table tr td table a"
    base_url: "http://idlebrain.com/movie/archive/"
    rating_css_path:  "html body table tbody tr td p font b font"
  gt:
    name: 'Gulte.com'
    url: "http://www.gulte.com/moviereviews"
    css_path:  "html body div.wrapper div.main div.container ul.list_more li a"
    base_url: ""
    rating_css_path:  "html body .rating span"
  123t:
    name: '123telugu'
    url: "http://www.123telugu.com/category/reviews/telugu-movie-reviews"
    css_path:  ".article-rel-wrapper a"
    base_url: ""
    rating_css_path:  ".post-content p span strong"
  toi:
    name: 'Times of India'
    url: 'http://timesofindia.indiatimes.com/entertainment/telugu/movie-reviews'
    css_path: 'div#articlenew .mr_listing_brd .mr_listing_right a'
    base_url: 'http://timesofindia.indiatimes.com/'
    rating_css_path: '.ratingMovie'
  ig:
    name: 'IndiaGlitz'
    url: 'http://www.indiaglitz.com/telugu-movie-reviews'
    css_path: 'table tr td table tr td a h1 a'
    base_url: ''
    rating_css_path: 'table div table div h3'
  tm:
    name: 'Telugu Mirchi'
    url: 'http://www.telugumirchi.com/en/reviews'
    css_path: '.post h2 a'
    base_url: ''
    rating_css_path: '.post-entry p b span'    
hindi:
  toi:
    name: 'Times of India'
    url: 'http://timesofindia.indiatimes.com/entertainment/hindi/movie-reviews'
    css_path: 'div#articlenew .mr_listing_brd .mr_listing_right a'
    base_url: 'http://timesofindia.indiatimes.com/'
    rating_css_path: '.ratingMovie'
  bh:
    name: 'Bollywood Hungama'
    url: 'http://www.bollywoodhungama.com/movies/reviews'
    css_path: '.mwidth560 .movlstrgt h2 a'
    base_url: 'http://www.bollywoodhungama.com/'
    rating_css_path: 'div#celeb_article_postview_tab span[itemprop=ratingValue]'
  ndtv:
    name: 'NDTV'
    url: 'http://movies.ndtv.com/movie-reviews/bollywood'
    css_path: '.ndmv-review-title a'
    base_url: ''
    rating_css_path: '.ndmv-review-breadcrumb-rating .rating'
