languages: [ 'telugu', 'hindi' ]
telugu:
  ga: 
    name: 'Great Andhra'
    url: "http://www.greatandhra.com/reviews.php"
    css_path:  "div.movies_page_news a"
    base_url: ""
    rating_css_path:  "html body div.content p strong span"     
  ib: 
    name: 'Idle Brain'
    url: "http://idlebrain.com/movie/archive/index.html"
    css_path:  "html body table tr td table tr td table tr td table a"
    base_url: "http://idlebrain.com/movie/archive/"
    rating_css_path:  "html body table tbody tr td p font b font"
  gt:
    name: 'Gulte.com'
    url: "http://www.gulte.com/moviereviews"
    css_path:  "html body div.wrapper div.main div.container ul.list_more li a"
    base_url: ""
    rating_css_path:  "html body .rating span"
  123t:
    name: '123telugu'
    url: "http://www.123telugu.com/category/reviews/telugu-movie-reviews"
    css_path:  ".article-rel-wrapper a"
    base_url: ""
    rating_css_path:  ".post-content p span strong"
  ko:
    name: 'Korada'
    url: "http://www.korada.com/telugu/category/reviews/"
    css_path:  "section#content div.item h3 a"
    base_url: ""
    rating_css_path:  "section#content h2 span"
  tpc:
    name: 'Tollywood Popcorn'
    url: "http://tollywoodpopcorn.com/category/reviews/"
    css_path:  "div.item_content h4 a"
    base_url: ""
    rating_css_path:  "div.review-total-wrapper span"
  toi:
    name: 'Times of India'
    url: 'http://timesofindia.indiatimes.com/entertainment/telugu/movie-reviews'
    css_path: 'div#articlenew .mr_listing_brd .mr_listing_right a'
    base_url: 'http://timesofindia.indiatimes.com/'
    rating_css_path: '.ratingMovie'
  ig:
    name: 'IndiaGlitz'
    url: 'http://www.indiaglitz.com/telugu-movie-reviews'
    css_path: 'table tr td table tr td a h1 a'
    base_url: ''
    rating_css_path: 'table div table div h3'
  tm:
    name: 'Telugu Mirchi'
    url: 'http://www.telugumirchi.com/en/reviews'
    css_path: '.post h2 a'
    base_url: ''
    rating_css_path: '.post-entry p b span'    
  ilc:
    name: 'I Luv Cinema'
    url: 'http://www.iluvcinema.in/telugu/reviews/movie-reviews/'
    css_path: '.cat_post .post-desc a'
    base_url: ''
    rating_css_path: 'div.entry-content-wrap span.entry-content h2 strong' 
  ah:
    name: 'Andhra Headlines'
    url: 'http://www.andhraheadlines.com/movies/reviews/'
    css_path: 'td.tabletitle a'
    base_url: 'http://www.andhraheadlines.com/'
    rating_css_path: 'span.ArticleText span span'
  sify:
    name: 'Sify Movies'
    url: 'http://www.sify.com/movies/reviews/category/telugu/'
    css_path: 'div.category-heading-wrapper a'
    base_url: ''
    rating_css_path: 'div.mreview-article-content-wrapper div p b'
hindi:
  toi:
    name: 'Times of India'
    url: 'http://timesofindia.indiatimes.com/entertainment/hindi/movie-reviews'
    css_path: 'div#articlenew .mr_listing_brd .mr_listing_right a'
    base_url: 'http://timesofindia.indiatimes.com/'
    rating_css_path: '.ratingMovie'
  bh:
    name: 'Bollywood Hungama'
    url: 'http://www.bollywoodhungama.com/movies/reviews'
    css_path: '.mwidth560 .movlstrgt h2 a'
    base_url: 'http://www.bollywoodhungama.com/'
    rating_css_path: 'div#celeb_article_postview_tab span[itemprop=ratingValue]'
  ndtv:
    name: 'NDTV'
    url: 'http://movies.ndtv.com/movie-reviews/bollywood'
    css_path: '.ndmv-review-title a'
    base_url: ''
    rating_css_path: '.ndmv-review-breadcrumb-rating .rating'
