languages: ['telugu']
telugu:
  ga: 
    name: 'Great Andhra'
    url: "http://www.greatandhra.com/reviews.php"
    css_path:  "div.movies_page_news a"
    base_url: ""
    rating_css_path:  "html body div.content p strong span"     
  ib: 
    name: 'Idle Brain'
    url: "http://idlebrain.com/movie/archive/index.html"
    css_path:  "html body table tr td table tr td table tr td table a"
    base_url: "http://idlebrain.com/movie/archive/"
    rating_css_path:  "html body table tbody tr td p font b font"
  gt:
    name: 'Gulte.com'
    url: "http://www.gulte.com/moviereviews"
    css_path:  "html body div.wrapper div.main div.container ul.list_more li a"
    base_url: ""
    rating_css_path:  "html body .rating span"

